sonar.projectKey=Lambda-Framesnap-Custom-Authorizer
sonar.projectName=Lambda-Framesnap-Custom-Authorizer
sonar.projectVersion=1.0

sonar.sources=Lambda-Authenticator/Lambda-Authenticator
sonar.tests=Lambda-Authenticator/Lambda-Authenticator.Tests
sonar.cs.vstest.reportsPaths=Lambda-Authenticator/Lambda-Authenticator.Tests/TestResults/*/coverage.cobertura.xml

sonar.coverage.exclusions=**/obj/**/*,**/bin/**/*,**/Properties/**/*,**/AssemblyInfo.cs,**/GlobalSuppressions.cs,**/*.Designer.cs,**/*.g.cs,**/*.g.i.cs,**/*.AssemblyAttributes.cs,**/Migrations/**/*,**/ModelSnapshot.cs,**/Startup.cs,**/Program.cs,**/Function.cs/&lt;FunctionHandler&gt;d__2.MoveNext,**/Function.cs/&lt;ValidateJwtToken&gt;d__3.MoveNext

sonar.cs.ignoreHeaderComments=true
sonar.cs.ignoreBlankLines=true
sonar.cs.ignoreComments=true

sonar.cs.vstest.reportsPaths=Lambda-Authenticator/Lambda-Authenticator.Tests/TestResults/*/coverage.cobertura.xml 